INSERT INTO category (name) VALUES ('Vestimentas');
INSERT INTO category (name) VALUES ('Acessorios');
INSERT INTO category (name) VALUES ('Armas');
INSERT INTO category (name) VALUES ('Joias');
INSERT INTO category (name) VALUES ('Embarcacoes');
INSERT INTO category (name) VALUES ('Diversos');

INSERT INTO country (name, code) VALUES ('Afeganistao', 'AFG');
INSERT INTO country (name, code) VALUES ('Africa do Sul', 'ZAF');
INSERT INTO country (name, code) VALUES ('Ilhas Alanda', 'ALA');
INSERT INTO country (name, code) VALUES ('Albania', 'ALB');
INSERT INTO country (name, code) VALUES ('Alemanha', 'DEU');
INSERT INTO country (name, code) VALUES ('Andorra', 'AND');
INSERT INTO country (name, code) VALUES ('Angola', 'AGO');
INSERT INTO country (name, code) VALUES ('Anguilla', 'AIA');
INSERT INTO country (name, code) VALUES ('Antarctida', 'ATA');
INSERT INTO country (name, code) VALUES ('Antigua e Barbuda', 'ATG');
INSERT INTO country (name, code) VALUES ('Antilhas Holandesas', 'ANT');
INSERT INTO country (name, code) VALUES ('Arabia Saudita', 'SAU');
INSERT INTO country (name, code) VALUES ('Argelia', 'DZA');
INSERT INTO country (name, code) VALUES ('Argentina', 'ARG');
INSERT INTO country (name, code) VALUES ('Armenia', 'ARM');
INSERT INTO country (name, code) VALUES ('Aruba', 'ABW');
INSERT INTO country (name, code) VALUES ('Australia', 'AUS');
INSERT INTO country (name, code) VALUES ('Austria', 'AUT');
INSERT INTO country (name, code) VALUES ('Azerbaijao', 'AZE');
INSERT INTO country (name, code) VALUES ('Bahamas', 'BHS');
INSERT INTO country (name, code) VALUES ('Bahrein', 'BHR');
INSERT INTO country (name, code) VALUES ('Bangladesh', 'BGD');
INSERT INTO country (name, code) VALUES ('Barbados', 'BRB');
INSERT INTO country (name, code) VALUES ('Belgica', 'BEL');
INSERT INTO country (name, code) VALUES ('Belize', 'BLZ');
INSERT INTO country (name, code) VALUES ('Benim', 'BEN');
INSERT INTO country (name, code) VALUES ('Bermudas', 'BMU');
INSERT INTO country (name, code) VALUES ('Bielorrussia', 'BLR');
INSERT INTO country (name, code) VALUES ('Butao', 'BTN');
INSERT INTO country (name, code) VALUES ('Bolivia', 'BOL');
INSERT INTO country (name, code) VALUES ('Bosnia e Herzegovina', 'BIH');
INSERT INTO country (name, code) VALUES ('Botsuana', 'BWA');
INSERT INTO country (name, code) VALUES ('Ilha Bouvet', 'BVT');
INSERT INTO country (name, code) VALUES ('Brasil', 'BRA');
INSERT INTO country (name, code) VALUES ('Brunei', 'BRN');
INSERT INTO country (name, code) VALUES ('Bulgaria', 'BGR');
INSERT INTO country (name, code) VALUES ('Burkina Faso', 'BFA');
INSERT INTO country (name, code) VALUES ('Burundi', 'BDI');
INSERT INTO country (name, code) VALUES ('Camboja', 'KHM');
INSERT INTO country (name, code) VALUES ('Camaroes', 'CMR');
INSERT INTO country (name, code) VALUES ('Canada', 'CAN');
INSERT INTO country (name, code) VALUES ('Cabo Verde', 'CPV');
INSERT INTO country (name, code) VALUES ('Ilhas Cayman', 'CYM');
INSERT INTO country (name, code) VALUES ('Cazaquistao', 'KAZ');
INSERT INTO country (name, code) VALUES ('Chade', 'TCD');
INSERT INTO country (name, code) VALUES ('Chile', 'CHL');
INSERT INTO country (name, code) VALUES ('China', 'CHN');
INSERT INTO country (name, code) VALUES ('Chipre', 'CYP');
INSERT INTO country (name, code) VALUES ('Ilha Christmas', 'CXR');
INSERT INTO country (name, code) VALUES ('Ilhas Cocos', 'CCK');
INSERT INTO country (name, code) VALUES ('Colombia', 'COL');
INSERT INTO country (name, code) VALUES ('Comores', 'COM');
INSERT INTO country (name, code) VALUES ('Congo', 'COG');
INSERT INTO country (name, code) VALUES ('Ilhas Cook', 'COK');
INSERT INTO country (name, code) VALUES ('Coreia do Norte', 'PRK');
INSERT INTO country (name, code) VALUES ('Coreia do Sul', 'KOR');
INSERT INTO country (name, code) VALUES ('Costa Rica', 'CRI');
INSERT INTO country (name, code) VALUES ('Costa do Marfim', 'CIV');
INSERT INTO country (name, code) VALUES ('Croacia', 'HRV');
INSERT INTO country (name, code) VALUES ('Cuba', 'CUB');
INSERT INTO country (name, code) VALUES ('Dinamarca', 'DNK');
INSERT INTO country (name, code) VALUES ('Djibouti', 'DJI');
INSERT INTO country (name, code) VALUES ('Dominica', 'DMA');
INSERT INTO country (name, code) VALUES ('Equador', 'ECU');
INSERT INTO country (name, code) VALUES ('Egito', 'EGY');
INSERT INTO country (name, code) VALUES ('El Salvador', 'SLV');
INSERT INTO country (name, code) VALUES ('Emirados Arabes Unidos', 'ARE');
INSERT INTO country (name, code) VALUES ('Eritreia', 'ERI');
INSERT INTO country (name, code) VALUES ('Escocia', 'SCO');
INSERT INTO country (name, code) VALUES ('Eslovaquia', 'SVK');
INSERT INTO country (name, code) VALUES ('Eslovenia', 'SVN');
INSERT INTO country (name, code) VALUES ('Espanha', 'ESP');
INSERT INTO country (name, code) VALUES ('Estados Unidos', 'USA');
INSERT INTO country (name, code) VALUES ('Ilhas Menores Distantes dos Estados Unidos', 'UMI');
INSERT INTO country (name, code) VALUES ('Estonia', 'EST');
INSERT INTO country (name, code) VALUES ('Etiopia', 'ETH');
INSERT INTO country (name, code) VALUES ('Ilhas Feroe', 'FRO');
INSERT INTO country (name, code) VALUES ('Fiji', 'FJI');
INSERT INTO country (name, code) VALUES ('Filipinas', 'PHL');
INSERT INTO country (name, code) VALUES ('Finlandia', 'FIN');
INSERT INTO country (name, code) VALUES ('Franca', 'FRA');
INSERT INTO country (name, code) VALUES ('Terras Austrais e Antarticas Francesas', 'ATF');
INSERT INTO country (name, code) VALUES ('Gabao', 'GAB');
INSERT INTO country (name, code) VALUES ('Gana', 'GHA');
INSERT INTO country (name, code) VALUES ('Gambia', 'GMB');
INSERT INTO country (name, code) VALUES ('Georgia', 'GEO');
INSERT INTO country (name, code) VALUES ('Ilhas Georgia do Sul e Sandwich do Sul', 'SGS');
INSERT INTO country (name, code) VALUES ('Gibraltar', 'GIB');
INSERT INTO country (name, code) VALUES ('Granada', 'GRD');
INSERT INTO country (name, code) VALUES ('Grecia', 'GRC');
INSERT INTO country (name, code) VALUES ('Gronelandia', 'GRL');
INSERT INTO country (name, code) VALUES ('Guadalupe', 'GLP');
INSERT INTO country (name, code) VALUES ('Guam', 'GUM');
INSERT INTO country (name, code) VALUES ('Guatemala', 'GTM');
INSERT INTO country (name, code) VALUES ('Guernsey', 'GGY');
INSERT INTO country (name, code) VALUES ('Guine', 'GIN');
INSERT INTO country (name, code) VALUES ('Guine-Bissau', 'GNB');
INSERT INTO country (name, code) VALUES ('Guine Equatorial', 'GNQ');
INSERT INTO country (name, code) VALUES ('Guiana', 'GUY');
INSERT INTO country (name, code) VALUES ('Guiana Francesa', 'GUF');
INSERT INTO country (name, code) VALUES ('Haiti', 'HTI');
INSERT INTO country (name, code) VALUES ('Ilha Heard e Ilhas McDonald', 'HMD');
INSERT INTO country (name, code) VALUES ('Honduras', 'HND');
INSERT INTO country (name, code) VALUES ('Hong Kong', 'HKG');
INSERT INTO country (name, code) VALUES ('Hungria', 'HUN');
INSERT INTO country (name, code) VALUES ('Iemen', 'YEM');
INSERT INTO country (name, code) VALUES ('India', 'IND');
INSERT INTO country (name, code) VALUES ('Indonesia', 'IDN');
INSERT INTO country (name, code) VALUES ('Inglaterra', 'ENG');
INSERT INTO country (name, code) VALUES ('Ira', 'IRN');
INSERT INTO country (name, code) VALUES ('Iraque', 'IRQ');
INSERT INTO country (name, code) VALUES ('Irlanda', 'IRL');
INSERT INTO country (name, code) VALUES ('Irlanda do Norte', 'NIR');
INSERT INTO country (name, code) VALUES ('Ilha de Man', 'IMN');
INSERT INTO country (name, code) VALUES ('Islandia', 'ISL');
INSERT INTO country (name, code) VALUES ('Israel', 'ISR');
INSERT INTO country (name, code) VALUES ('Italia', 'ITA');
INSERT INTO country (name, code) VALUES ('Jamaica', 'JAM');
INSERT INTO country (name, code) VALUES ('Japao', 'JPN');
INSERT INTO country (name, code) VALUES ('Jersey', 'JEY');
INSERT INTO country (name, code) VALUES ('Jordania', 'JOR');
INSERT INTO country (name, code) VALUES ('Kiribati', 'KIR');
INSERT INTO country (name, code) VALUES ('Kosovo', 'KOS');
INSERT INTO country (name, code) VALUES ('Kuwait', 'KWT');
INSERT INTO country (name, code) VALUES ('Laos', 'LAO');
INSERT INTO country (name, code) VALUES ('Letonia', 'LVA');
INSERT INTO country (name, code) VALUES ('Lesoto', 'LSO');
INSERT INTO country (name, code) VALUES ('Libano', 'LBN');
INSERT INTO country (name, code) VALUES ('Liberia', 'LBR');
INSERT INTO country (name, code) VALUES ('Libia', 'LBY');
INSERT INTO country (name, code) VALUES ('Liechtenstein', 'LIE');
INSERT INTO country (name, code) VALUES ('Lituania', 'LTU');
INSERT INTO country (name, code) VALUES ('Luxemburgo', 'LUX');
INSERT INTO country (name, code) VALUES ('Macau', 'MAC');
INSERT INTO country (name, code) VALUES ('Macedonia', 'MKD');
INSERT INTO country (name, code) VALUES ('Madagascar', 'MDG');
INSERT INTO country (name, code) VALUES ('Malasia', 'MYS');
INSERT INTO country (name, code) VALUES ('Malaui', 'MWI');
INSERT INTO country (name, code) VALUES ('Maldivas', 'MDV');
INSERT INTO country (name, code) VALUES ('Mali', 'MLI');
INSERT INTO country (name, code) VALUES ('Malta', 'MLT');
INSERT INTO country (name, code) VALUES ('Ilhas Malvinas', 'FLK');
INSERT INTO country (name, code) VALUES ('Ilhas Marshall', 'MHL');
INSERT INTO country (name, code) VALUES ('Marianas Setentrionais', 'MNP');
INSERT INTO country (name, code) VALUES ('Marrocos', 'MAR');
INSERT INTO country (name, code) VALUES ('Martinica', 'MTQ');
INSERT INTO country (name, code) VALUES ('Mauritania', 'MRT');
INSERT INTO country (name, code) VALUES ('Mauricia', 'MUS');
INSERT INTO country (name, code) VALUES ('Mayotte', 'MYT');
INSERT INTO country (name, code) VALUES ('Mexico', 'MEX');
INSERT INTO country (name, code) VALUES ('Mianmar', 'MMR');
INSERT INTO country (name, code) VALUES ('Estados Federados da Micronesia', 'FSM');
INSERT INTO country (name, code) VALUES ('Moldavia', 'MDA');
INSERT INTO country (name, code) VALUES ('Monaco', 'MCO');
INSERT INTO country (name, code) VALUES ('Mongolia', 'MNG');
INSERT INTO country (name, code) VALUES ('Montenegro', 'MNE');
INSERT INTO country (name, code) VALUES ('Montserrat', 'MSR');
INSERT INTO country (name, code) VALUES ('Mocambique', 'MOZ');
INSERT INTO country (name, code) VALUES ('Namibia', 'NAM');
INSERT INTO country (name, code) VALUES ('Nauru', 'NRU');
INSERT INTO country (name, code) VALUES ('Nepal', 'NPL');
INSERT INTO country (name, code) VALUES ('Nova Caledonia', 'NCL');
INSERT INTO country (name, code) VALUES ('Nova Zelandia', 'NZL');
INSERT INTO country (name, code) VALUES ('Nicaragua', 'NIC');
INSERT INTO country (name, code) VALUES ('Niger', 'NER');
INSERT INTO country (name, code) VALUES ('Nigeria', 'NGA');
INSERT INTO country (name, code) VALUES ('Niue', 'NIU');
INSERT INTO country (name, code) VALUES ('Ilha Norfolk', 'NFK');
INSERT INTO country (name, code) VALUES ('Noruega', 'NOR');
INSERT INTO country (name, code) VALUES ('Oma', 'OMN');
INSERT INTO country (name, code) VALUES ('Pais de Gales', 'WAL');
INSERT INTO country (name, code) VALUES ('Paises Baixos', 'NLD');
INSERT INTO country (name, code) VALUES ('Palau', 'PLW');
INSERT INTO country (name, code) VALUES ('Palestina', 'PSE');
INSERT INTO country (name, code) VALUES ('Panama', 'PAN');
INSERT INTO country (name, code) VALUES ('Papua-Nova Guine', 'PNG');
INSERT INTO country (name, code) VALUES ('Paquistao', 'PAK');
INSERT INTO country (name, code) VALUES ('Paraguai', 'PRY');
INSERT INTO country (name, code) VALUES ('Peru', 'PER');
INSERT INTO country (name, code) VALUES ('Pitcairn', 'PCN');
INSERT INTO country (name, code) VALUES ('Polinesia Francesa', 'PYF');
INSERT INTO country (name, code) VALUES ('Polonia', 'POL');
INSERT INTO country (name, code) VALUES ('Portugal', 'PRT');
INSERT INTO country (name, code) VALUES ('Porto Rico', 'PRI');
INSERT INTO country (name, code) VALUES ('Qatar', 'QAT');
INSERT INTO country (name, code) VALUES ('Quenia', 'KEN');
INSERT INTO country (name, code) VALUES ('Quirguistao', 'KGZ');
INSERT INTO country (name, code) VALUES ('Reino Unido', 'GBR');
INSERT INTO country (name, code) VALUES ('Territorio Britanico do Oceano Indico', 'IOT');
INSERT INTO country (name, code) VALUES ('Ilhas Virgens Britanicas', 'VGB');
INSERT INTO country (name, code) VALUES ('Republica Centro-Africana', 'CAF');
INSERT INTO country (name, code) VALUES ('Republica Checa', 'CZE');
INSERT INTO country (name, code) VALUES ('Republica Democratica do Congo', 'COD');
INSERT INTO country (name, code) VALUES ('Republica Dominicana', 'DOM');
INSERT INTO country (name, code) VALUES ('Taiwan', 'TWN');
INSERT INTO country (name, code) VALUES ('Reuniao', 'REU');
INSERT INTO country (name, code) VALUES ('Romenia', 'ROU');
INSERT INTO country (name, code) VALUES ('Russia', 'RUS');
INSERT INTO country (name, code) VALUES ('Ruanda', 'RWA');
INSERT INTO country (name, code) VALUES ('Saara Ocidental', 'ESH');
INSERT INTO country (name, code) VALUES ('Ilhas Salomao', 'SLB');
INSERT INTO country (name, code) VALUES ('Samoa', 'WSM');
INSERT INTO country (name, code) VALUES ('Samoa Americana', 'ASM');
INSERT INTO country (name, code) VALUES ('Saint-Barthelemy', 'BLM');
INSERT INTO country (name, code) VALUES ('Santa Helena (territorio)', 'SHN');
INSERT INTO country (name, code) VALUES ('Santa Lucia', 'LCA');
INSERT INTO country (name, code) VALUES ('Saint Martin', 'MAF');
INSERT INTO country (name, code) VALUES ('Sao Cristovao e Nevis', 'KNA');
INSERT INTO country (name, code) VALUES ('Sao Pedro e Miquelao', 'SPM');
INSERT INTO country (name, code) VALUES ('Sao Vicente e Granadinas', 'VCT');
INSERT INTO country (name, code) VALUES ('Sao Marinho', 'SMR');
INSERT INTO country (name, code) VALUES ('Sao Tome e Principe', 'STP');
INSERT INTO country (name, code) VALUES ('Senegal', 'SEN');
INSERT INTO country (name, code) VALUES ('Serra Leoa', 'SLE');
INSERT INTO country (name, code) VALUES ('Servia', 'SRB');
INSERT INTO country (name, code) VALUES ('Seychelles', 'SYC');
INSERT INTO country (name, code) VALUES ('Singapura', 'SGP');
INSERT INTO country (name, code) VALUES ('Siria', 'SYR');
INSERT INTO country (name, code) VALUES ('Somalia', 'SOM');
INSERT INTO country (name, code) VALUES ('Sri Lanka', 'LKA');
INSERT INTO country (name, code) VALUES ('Sudao', 'SDN');
INSERT INTO country (name, code) VALUES ('Suecia', 'SWE');
INSERT INTO country (name, code) VALUES ('Suazilandia', 'SWZ');
INSERT INTO country (name, code) VALUES ('Suica', 'CHE');
INSERT INTO country (name, code) VALUES ('Suriname', 'SUR');
INSERT INTO country (name, code) VALUES ('Svalbard', 'SJM');
INSERT INTO country (name, code) VALUES ('Tadjiquistao', 'TJK');
INSERT INTO country (name, code) VALUES ('Tailandia', 'THA');
INSERT INTO country (name, code) VALUES ('Tanzania', 'TZA');
INSERT INTO country (name, code) VALUES ('Timor-Leste', 'TLS');
INSERT INTO country (name, code) VALUES ('Togo', 'TGO');
INSERT INTO country (name, code) VALUES ('Toquelau', 'TKL');
INSERT INTO country (name, code) VALUES ('Tonga', 'TON');
INSERT INTO country (name, code) VALUES ('Trinidad e Tobago', 'TTO');
INSERT INTO country (name, code) VALUES ('Tunisia', 'TUN');
INSERT INTO country (name, code) VALUES ('Turcomenistao', 'TKM');
INSERT INTO country (name, code) VALUES ('Turquia', 'TUR');
INSERT INTO country (name, code) VALUES ('Turcas e Caicos', 'TCA');
INSERT INTO country (name, code) VALUES ('Tuvalu', 'TUV');
INSERT INTO country (name, code) VALUES ('Ucrania', 'UKR');
INSERT INTO country (name, code) VALUES ('Uganda', 'UGA');
INSERT INTO country (name, code) VALUES ('Ilhas Virgens Americanas', 'VIR');
INSERT INTO country (name, code) VALUES ('Uruguai', 'URY');
INSERT INTO country (name, code) VALUES ('Uzbequistao', 'UZB');
INSERT INTO country (name, code) VALUES ('Vanuatu', 'VUT');
INSERT INTO country (name, code) VALUES ('Vaticano', 'VAT');
INSERT INTO country (name, code) VALUES ('Venezuela', 'VEN');
INSERT INTO country (name, code) VALUES ('Vietname', 'VNM');
INSERT INTO country (name, code) VALUES ('Wallis e Futuna', 'WLF');
INSERT INTO country (name, code) VALUES ('Zambia', 'ZMB');
INSERT INTO country (name, code) VALUES ('Zimbabue', 'ZWE');


INSERT INTO supplier (name, code, country_id, phone, email) VALUES ('Einsteins Front Flip', 'ENG1', 5, '+49-157-555-5770', 'germ@ny.deu');
INSERT INTO supplier (name, code, country_id, phone, email) VALUES ('Westminster Abbey INC.', 'GER1', 109, null, 'will.i.am@shakespeare.com');

INSERT INTO brand (name, country_id) VALUES ('Swarovski AG', 18);

INSERT INTO product (name, description, price, category_id, brand_id, rating) VALUES ('Esmeralda Preta 50k', 'Joia rarissma encontrada no sertao nordestino brasileiro', 50000.00, 4, 1, 8.5);

INSERT INTO "user" (name, username, password) VALUES ('Administrador', 'admin', '$2a$10$.PVIfB07x.SfMYTcToxL0.yxcLWU0GbS2NUO1W1QAvqMm/TsFhVem');
INSERT INTO "user" (name, username, password) VALUES ('Teste', 'teste', '$2a$10$.PVIfB07x.SfMYTcToxL0.yxcLWU0GbS2NUO1W1QAvqMm/TsFhVem');

INSERT INTO "role" (name) VALUES ('ROLE_ADMIN');
INSERT INTO "role" (name) VALUES ('ROLE_USER');

INSERT INTO user_roles (user_id, roles_id) VALUES (1, 1);
INSERT INTO user_roles (user_id, roles_id) VALUES (1, 2);
INSERT INTO user_roles (user_id, roles_id) VALUES (2, 2);
